spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
buildStrategies:

  - monster: 11965622274 #Lushen
    priority: 1
    buildPreferences:
      - type: WITHIN_REQUIRED_RANGE
        attribute: CRITICAL_RATE
        minimumValue: 100
      - type: WITHIN_REQUIRED_RANGE
        attribute: SPEED
        minimumValue: 174
      - type: AS_HIGH_AS_POSSIBLE
        attribute: ATTACK
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_DAMAGE

  - monster: 15203246381 #Kro
    priority: 2
    buildPreferences:
      - type: WITHIN_REQUIRED_RANGE
        attribute: CRITICAL_RATE
        minimumValue: 100
      - type: WITHIN_REQUIRED_RANGE
        attribute: SPEED
        minimumValue: 153
        maximumValue: 163
      - type: AS_HIGH_AS_POSSIBLE
        attribute: ATTACK
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_DAMAGE