spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
buildStrategies:
  - monster: 11965622274 #Lushen
    priority: 1
    buildPreferences:
      - type: WITHIN_REQUIRED_RANGE
        attribute: CRITICAL_RATE
        minimumValue: 100
        priority: 1
      - type: WITHIN_REQUIRED_RANGE
        attribute: SPEED
        minimumValue: 223
        priority: 2
      - type: AS_HIGH_AS_POSSIBLE
        attribute: ATTACK
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_DAMAGE

  - monster: 15203246381 #Kro
    priority: 2
    buildPreferences:
      - type: WITHIN_REQUIRED_RANGE
        attribute: CRITICAL_RATE
        minimumValue: 100
        priority: 1
      - type: WITHIN_REQUIRED_RANGE
        attribute: SPEED
        minimumValue: 148
        priority: 2
      - type: AS_HIGH_AS_POSSIBLE
        attribute: ATTACK
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_DAMAGE

  - monster: 14607903174 #Naomi
    priority: 3
    buildPreferences:
      - type: WITHIN_REQUIRED_RANGE
        attribute: SPEED
        minimumValue: 146
        priority: 2
      - type: AS_HIGH_AS_POSSIBLE
        attribute: ATTACK
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_DAMAGE

  - monster: 14068143793 #Loren
    priority: 4
    buildPreferences:
      - type: WITHIN_REQUIRED_RANGE
        attribute: SPEED
        minimumValue: 159
        priority: 1
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_RATE
      - type: AS_HIGH_AS_POSSIBLE
        attribute: ATTACK
      - type: AS_HIGH_AS_POSSIBLE
        attribute: CRITICAL_DAMAGE

  - monster: 12230300232 #Fran
    priority: 5
    buildPreferences:
      - type: AS_HIGH_AS_POSSIBLE
        attribute: SPEED
      - type: AS_HIGH_AS_POSSIBLE
        attribute: HIT_POINTS
      - type: AS_HIGH_AS_POSSIBLE
        attribute: SPEED